export const DATA = [
  {
    id: 1,
    productName: "Fixflex",
    brand: "O'Keefe-Cartwright",
    stockQty: 45,
    price: 39908,
    image: "http://dummyimage.com/151x128.png/5fa2dd/ffffff",
  },
  {
    id: 2,
    productName: "Tres-Zap",
    brand: "Baumbach LLC",
    stockQty: 27,
    price: 25116,
    image: "http://dummyimage.com/243x128.jpg/dddddd/000000",
  },
  {
    id: 3,
    productName: "Daltfresh",
    brand: "Kshlerin-Oberbrunner",
    stockQty: 54,
    price: 86966,
    image: "http://dummyimage.com/180x156.png/cc0000/ffffff",
  },
  {
    id: 4,
    productName: "Redhold",
    brand: "Klein, Cormier and Crona",
    stockQty: 36,
    price: 62751,
    image: "http://dummyimage.com/113x211.png/5fa2dd/ffffff",
  },
  {
    id: 5,
    productName: "Zamit",
    brand: "Waters-O'Hara",
    stockQty: 3,
    price: 68309,
    image: "http://dummyimage.com/108x181.jpg/cc0000/ffffff",
  },
  {
    id: 6,
    productName: "Temp",
    brand: "Ryan-Reilly",
    stockQty: 5,
    price: 6502,
    image: "http://dummyimage.com/201x206.jpg/cc0000/ffffff",
  },
  {
    id: 7,
    productName: "Span",
    brand: "Kertzmann and Sons",
    stockQty: 75,
    price: 5672,
    image: "http://dummyimage.com/151x104.bmp/ff4444/ffffff",
  },
  {
    id: 8,
    productName: "Pannier",
    brand: "Padberg-Nolan",
    stockQty: 4,
    price: 5420,
    image: "http://dummyimage.com/178x150.png/dddddd/000000",
  },
  {
    id: 9,
    productName: "Zaam-Dox",
    brand: "West Inc",
    stockQty: 26,
    price: 61016,
    image: "http://dummyimage.com/220x198.jpg/5fa2dd/ffffff",
  },
  {
    id: 10,
    productName: "Zoolab",
    brand: "Spinka-Dickens",
    stockQty: 58,
    price: 83265,
    image: "http://dummyimage.com/114x100.jpg/5fa2dd/ffffff",
  },
];
